import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./shared/Footer";
import Header from "./shared/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <main className="container mx-auto max-h-screen">
         <Header/>
       {children}
       <Footer/>
       </main>
        
        </body>
    </html>
  );
}
